# Configuration embedding file 1 - Microservice Config
service:
  name: "user-service-1"
  version: "2.1.1"
  environment: "production"
  port: 3001
  host: "0.0.0.0"

database:
  host: "db-cluster-1.example.com"
  port: 5432
  name: "user_db_1"
  username: "service_user_1"
  password: "${DB_PASSWORD}"
  ssl:
    enabled: true
    mode: "require"
  pool:
    min: 5
    max: 50
    acquire: 30000
    idle: 10000

cache:
  redis:
    host: "redis-cluster-1.example.com"
    port: 6379
    password: "${REDIS_PASSWORD}"
    db: 0
    maxConnections: 100

logging:
  level: "info"
  format: "json"
  output: "stdout"
  timestamp: true
  correlationId: true

security:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: 3600
    refreshExpiration: 604800
  cors:
    origins:
      - "https://app1.example.com"
      - "https://admin1.example.com"
    methods: ["GET", "POST", "PUT", "DELETE"]
    headers: ["Content-Type", "Authorization"]
