# Configuration embedding file 2 - Microservice Config
service:
  name: "user-service-2"
  version: "2.2.1"
  environment: "production"
  port: 3002
  host: "0.0.0.0"

database:
  host: "db-cluster-2.example.com"
  port: 5432
  name: "user_db_2"
  username: "service_user_2"
  password: "${DB_PASSWORD}"
  ssl:
    enabled: true
    mode: "require"
  pool:
    min: 5
    max: 50
    acquire: 30000
    idle: 10000

cache:
  redis:
    host: "redis-cluster-2.example.com"
    port: 6379
    password: "${REDIS_PASSWORD}"
    db: 0
    maxConnections: 100

logging:
  level: "info"
  format: "json"
  output: "stdout"
  timestamp: true
  correlationId: true

security:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: 3600
    refreshExpiration: 604800
  cors:
    origins:
      - "https://app2.example.com"
      - "https://admin2.example.com"
    methods: ["GET", "POST", "PUT", "DELETE"]
    headers: ["Content-Type", "Authorization"]
